### PR TITLE
Removed warning from well completion documentation

### PR DESCRIPTION
**Pull request by lindjoha**
Removed the warning about ignoring WELOPEN lines that are referring to COMPLUMP numbers. This is now fixed in ecl2df.

### CODE REVIEW

**Review by HansKallekleiv — CHANGES_REQUESTED** [review]
Bump the `libecl` requirement in `setup.py`?

**Comment by anders-kiaer** [comment]
> Bump the `ecl2df` requirement in `setup.py`?

I had the same thought, but looks like it is not released yet in `ecl2df` (https://github.com/equinor/ecl2df/pull/333). Maybe it can be considered a "bug fix" in `ecl2df` @lindjoha and therefore we can remove the warning on our side and still not bump `ecl2df`?

**Comment by lindjoha** [comment]
I suppose a new release of ecl2df isn't very far away. This new functionality was intended to go into the september release. So I'm not sure. The plugin is not depending on this functionality of course.

**Comment by anders-kiaer** [comment]
> I suppose a new release of `ecl2df `isn't very far away. This new functionality was intended to go into the september release. So I'm not sure. The plugin is not depending on this functionality of course.

:+1: Let's merge. We will bump the `webviz-subsurface-components`requirement anyway in `setup.py`later when that has an official september release. We could consider doing the same for `ecl2df`.

**Review by anders-kiaer — APPROVED** [review]

**Pull request merged**
