### PR TITLE
black 20.8b1 updates

### LINKED ISSUE #423: Black 20.8b1 style checking
New style check errors with new black version blocking CI 🟢

### PR DESCRIPTION
**Pull request by asnyv**
Code style updates to get 🟢 from new `black` version

---

### Contributor checklist

- [X] :tada: This PR closes #423. 
- [ ] ~~:scroll: I have broken down my PR into the following tasks:~~
- [ ] ~~:robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.~~
- [ ] ~~:book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.~~

### CODE REVIEW

**Review by anders-kiaer — COMMENTED** [review]
Add/update `>=` for `black` in `setup.py`?

Does the indentation of docstrings work as expected in the generated docs?

**Comment by asnyv** [comment]
> Add/update `>=` for `black` in `setup.py`?
- Good idea
> Does the indentation of docstrings work as expected in the generated docs?
 - No 🙈 have to fix that in webviz-config I guess? (or ignore it here)

**Comment by asnyv** [comment]
Docs should work as before after [this PR in webviz-config is merged](https://github.com/equinor/webviz-config/pull/271)

**Review by HansKallekleiv — APPROVED** [review]
👍

**Pull request merged**
