### PR TITLE
Extend column name obs->observed for readability

### PR DESCRIPTION
**Pull request by berland**
This will prepare webviz for a possible upcoming change in
scripts generating the input to the rft plotter plugin.

This change should be backwards compatible.

*Insert a description of your pull request (PR) here, and check off the boxes below when they are done.*

---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

### CODE REVIEW

**Review by HansKallekleiv — APPROVED** [review]
LGTM 👍

**Comment by anders-kiaer** [comment]
Thanks @berland 

> This change should be backwards compatible.

Will it be backward compatible by the corresponding forward model having e.g. both `OBS` and `OBSERVED` for some time? Is there some corresponding PR in https://github.com/equinor/semeio we can track/link to here?

**Comment by berland** [comment]
https://github.com/equinor/subscript/pull/195 is the script to be compatible versus. Backwards compatibility applies to non-published project-locally installed precursor to `merge_rft_ertobs` in  subscript.

**Comment by berland** [comment]
Recommended to merge to avoid incompatibility with subscript in Komodo.

**Comment by anders-kiaer** [comment]
Will get this in after @HansKallekleiv found a solution for #471 👍 Unstable tests (not related to this PR) currently blocks it from going 🟢

**Pull request merged**
